version: "3"

services:
  eventstore.db:
    image: eventstore/eventstore:20.10.0-buster-slim
    environment:
      EVENTSTORE_CLUSTER_SIZE: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_RUN_PROJECTIONS: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_START_STANDARD_PROJECTIONS: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_EXT_TCP_PORT: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_EXT_HTTP_PORT: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_INSECURE: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_ENABLE_EXTERNAL_TCP: ${EVENTSTORE_CLUSTER_SIZE}
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: ${EVENTSTORE_CLUSTER_SIZE}
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore-volume-data:/data/lib/eventstore
      - eventstore-volume-logs:/data/log/eventstore

  mongo.db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/mongodb
    ports:
      - "27077:27017"

  weather.service:
    depends_on:
      - eventstore.db
      - mongo.db
    restart: always
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/data/app
      - /data/app/node_modules
    env_file: .env

volumes:
  mongodata:
  eventstore-volume-data:
  eventstore-volume-logs:
