version: "3"

services:
  mongo.db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/mongodb
    ports:
      - "27077:27017"

  weather.service:
    depends_on:
      - mongo.db
    restart: always
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/data/app
      - /data/app/node_modules
    env_file: .env

volumes:
  mongodata:
