version: "3"

services:
  weather.service:
    depends_on:
      - mongo.db
    restart: always
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - MONGODB_URI=mongodb://nestmongo/weather
    volumes:
      - .:/data/app
      - /data/app/node_modules
    env_file: .env

  mongo.db:
    image: mongo
    container_name: nestmongo
    volumes:
      - mongo_data:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_DATABASE: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

volumes:
  mongo_data:
