version: "3"

services:
  mongo.db:
    image: mongo
    container_name: weather_mongo_db
    volumes:
      - weather_mongo_data:/data/mongodb
    ports:
      - "27077:27017"

  weather.service:
    depends_on:
      - mongo.db
    restart: always
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - MONGODB_URI=mongodb://weather
    volumes:
      - .:/data/app
      - /data/app/node_modules
    env_file: .env

volumes:
  weather_mongo_data:
